#!/bin/bash
# program-srk-fuses.sh — Program SRK hash fuses via Linux nvmem interface
#
# WARNING: This programs OCOTP fuses — ONE-TIME PROGRAMMABLE, IRREVERSIBLE
#
# Usage: program-srk-fuses.sh <srk_fuse_bin>
#
# Arguments:
#   srk_fuse_bin - Path to SRK_1_2_3_4_fuse.bin (32 bytes, generated by srktool)
#
# Requirements:
#   - Must be run as root
#   - nvmem write access to /sys/bus/nvmem/devices/imx-ocotp0/nvmem
#   - 1.8V supply on VDD_FUSE (check hardware requirements)
#
# VERIFY THREE TIMES BEFORE RUNNING

set -euo pipefail

SRK_FUSE_BIN="${1:?Usage: $0 <srk_fuse_bin>}"
NVMEM_PATH="/sys/bus/nvmem/devices/imx-ocotp0/nvmem"

# ─────────────────────────────────────────────
# Pre-flight checks
# ─────────────────────────────────────────────

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Must run as root" >&2
    exit 1
fi

if [ ! -f "$SRK_FUSE_BIN" ]; then
    echo "ERROR: SRK fuse binary not found: $SRK_FUSE_BIN" >&2
    exit 1
fi

FUSE_SIZE=$(wc -c < "$SRK_FUSE_BIN")
if [ "$FUSE_SIZE" -ne 32 ]; then
    echo "ERROR: SRK fuse binary must be exactly 32 bytes, got $FUSE_SIZE" >&2
    exit 1
fi

if [ ! -w "$NVMEM_PATH" ]; then
    echo "ERROR: Cannot write to $NVMEM_PATH" >&2
    echo "Ensure kernel has nvmem write support (CONFIG_NVMEM_WRITE=y)" >&2
    exit 1
fi

# ─────────────────────────────────────────────
# Display values to be programmed
# ─────────────────────────────────────────────

echo "=== SRK FUSE PROGRAMMING ==="
echo "WARNING: THIS IS IRREVERSIBLE"
echo ""
echo "SRK fuse file: $SRK_FUSE_BIN"
echo "SHA-256:        $(sha256sum "$SRK_FUSE_BIN" | cut -d' ' -f1)"
echo ""
echo "Values to program (Bank 3, Words 0-7):"

python3 << PYEOF
import struct
data = open('${SRK_FUSE_BIN}', 'rb').read()
for i in range(8):
    word = struct.unpack('<I', data[i*4:(i+1)*4])[0]
    print(f'  Bank 3, Word {i}: 0x{word:08X}')
PYEOF

# ─────────────────────────────────────────────
# Check current fuse state
# ─────────────────────────────────────────────
echo ""
echo "Current fuse values (should be all zeros):"
CURRENT=$(dd if="$NVMEM_PATH" bs=4 skip=24 count=8 2>/dev/null | od -An -tx4)
echo "$CURRENT"

# Check if already programmed
if echo "$CURRENT" | grep -qv "00000000"; then
    echo ""
    echo "WARNING: Fuses appear to already be programmed!"
    echo "Do NOT re-program if the existing values match what you want."
    echo ""
    read -r -p "Compare existing values with new values and continue? [yes/NO]: " CONFIRM
    [ "$CONFIRM" = "yes" ] || { echo "Aborted."; exit 1; }
fi

# ─────────────────────────────────────────────
# Final confirmation
# ─────────────────────────────────────────────
echo ""
echo "FINAL CONFIRMATION REQUIRED"
echo "Type 'PROGRAM' (all caps) to proceed:"
read -r CONFIRM
if [ "$CONFIRM" != "PROGRAM" ]; then
    echo "Aborted — nothing was programmed."
    exit 1
fi

# ─────────────────────────────────────────────
# Program fuses via nvmem
# ─────────────────────────────────────────────
echo ""
echo "Programming fuses..."

OFFSET=$(( 24 * 4 ))  # Bank 3, Word 0 = (3*8 + 0) * 4 = 96 = 0x60

python3 << PYEOF
import struct

data = open('${SRK_FUSE_BIN}', 'rb').read()
offset = 3 * 8 * 4  # Bank 3, Word 0

with open('${NVMEM_PATH}', 'r+b') as f:
    f.seek(offset)
    f.write(data)

print("Fuses written successfully")
PYEOF

# ─────────────────────────────────────────────
# Verify
# ─────────────────────────────────────────────
echo ""
echo "Verifying programmed values..."

python3 << PYEOF
import struct, hashlib

# Read what was written
with open('${NVMEM_PATH}', 'rb') as f:
    f.seek(3 * 8 * 4)
    actual = f.read(32)

# Read expected
expected = open('${SRK_FUSE_BIN}', 'rb').read()

if actual == expected:
    print("VERIFICATION PASSED: Fuse values match expected")
    for i in range(8):
        word = struct.unpack('<I', actual[i*4:(i+1)*4])[0]
        print(f'  Bank 3, Word {i}: 0x{word:08X}')
else:
    print("VERIFICATION FAILED: Fuse values do not match!")
    print(f"Expected: {expected.hex()}")
    print(f"Actual:   {actual.hex()}")
    exit(1)
PYEOF

echo ""
echo "SRK fuse programming complete."
echo "Reboot to verify HAB status."
