#!/bin/bash
# generate-hab-keys.sh
# Generates HABv4 key hierarchy using NXP CST
#
# SECURITY: Run this ONLY on an air-gapped system
# SECURITY: Store output in an HSM or encrypted offline storage
#
# Dependencies: NXP Code Signing Tool (CST)
# Usage: CST_PATH=/opt/cst ./generate-hab-keys.sh [output_dir]

set -euo pipefail

# Configuration
CST_PATH="${CST_PATH:-/opt/cst}"
OUTPUT_DIR="${1:-$(pwd)/hab-keys-$(date +%Y%m%d-%H%M%S)}"
KEY_LENGTH="${KEY_LENGTH:-2048}"
EXPIRY_DAYS="${EXPIRY_DAYS:-3650}"
NUM_SRK="${NUM_SRK:-4}"

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

check_prerequisites() {
    log_info "Checking prerequisites..."

    if [ ! -d "$CST_PATH" ]; then
        log_error "CST not found at $CST_PATH"
        log_error "Install NXP Code Signing Tool first"
        log_error "Download from nxp.com (free registration required)"
        exit 1
    fi

    if [ ! -x "$CST_PATH/keys/hab4_pki_tree.sh" ]; then
        log_error "hab4_pki_tree.sh not found in $CST_PATH/keys/"
        log_error "Verify CST installation is complete"
        exit 1
    fi

    if [ ! -x "$CST_PATH/linux64/bin/srktool" ]; then
        log_error "srktool not found in $CST_PATH/linux64/bin/"
        log_error "Verify CST linux64 binaries are present and executable"
        exit 1
    fi

    if ! command -v openssl &>/dev/null; then
        log_error "openssl not found"
        log_error "Install: apt-get install openssl"
        exit 1
    fi

    # Check kernel entropy pool
    AVAIL=$(cat /proc/sys/kernel/random/entropy_avail)
    if [ "$AVAIL" -lt 1000 ]; then
        log_warn "Low entropy: $AVAIL bits available (recommend >2000)"
        log_warn "Consider: apt-get install haveged && systemctl start haveged"
        log_warn "Or move the mouse / type on keyboard to generate entropy"
        read -rp "Continue anyway? [y/N] " yn
        if [[ "$yn" != "y" && "$yn" != "Y" ]]; then
            exit 1
        fi
    fi

    # Check we are not running as root (keys should be owned by a real user)
    if [ "$(id -u)" = "0" ]; then
        log_warn "Running as root. Keys will be owned by root."
        log_warn "Consider running as a dedicated non-root signing user."
    fi

    log_info "Prerequisites OK (entropy: $AVAIL bits, CST: $CST_PATH)"
}

security_warning() {
    echo ""
    echo -e "${RED}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║           SECURITY CRITICAL OPERATION                     ║${NC}"
    echo -e "${RED}║                                                            ║${NC}"
    echo -e "${RED}║  You are about to generate HABv4 signing keys.            ║${NC}"
    echo -e "${RED}║                                                            ║${NC}"
    echo -e "${RED}║  These keys will be BURNED into device fuses.             ║${NC}"
    echo -e "${RED}║  Once burned, they CANNOT be changed.                     ║${NC}"
    echo -e "${RED}║  If private keys are LOST or COMPROMISED, affected        ║${NC}"
    echo -e "${RED}║  devices cannot be re-provisioned.                        ║${NC}"
    echo -e "${RED}║                                                            ║${NC}"
    echo -e "${RED}║  Ensure you are on an AIR-GAPPED system.                  ║${NC}"
    echo -e "${RED}║  Ensure you have a secure backup plan for the keys.       ║${NC}"
    echo -e "${RED}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Configuration:"
    echo "  Output directory : $OUTPUT_DIR"
    echo "  Key length       : ${KEY_LENGTH} bits"
    echo "  Expiry           : ${EXPIRY_DAYS} days (~$(( EXPIRY_DAYS / 365 )) years)"
    echo "  Number of SRKs   : $NUM_SRK"
    echo ""
    read -rp "Type 'I UNDERSTAND' to continue: " confirmation
    if [ "$confirmation" != "I UNDERSTAND" ]; then
        log_error "Confirmation not received. Exiting."
        exit 1
    fi
}

generate_keys() {
    log_info "Creating output directory: $OUTPUT_DIR"
    mkdir -p "$OUTPUT_DIR"/{crts,keys}

    log_info "Generating HABv4 key hierarchy..."
    log_info "This may take a minute depending on key length and system entropy."

    # CST's hab4_pki_tree.sh reads from stdin in an interactive prompt.
    # The responses below correspond to:
    #   "Do you want to use an existing CA key?" -> y (use CA1 generated by CST)
    #   "Enter CA key name" -> CA1
    #   "Enter key length" -> $KEY_LENGTH
    #   "Enter certificate duration" -> $EXPIRY_DAYS
    #   "How many Super Root Keys should be generated?" -> $NUM_SRK
    #   "Do you want the SRK certificates to have the CA flag set?" -> n

    pushd "$CST_PATH/keys" > /dev/null

    printf 'y\nCA1\n%s\n%s\n%s\nn\n' \
        "$KEY_LENGTH" "$EXPIRY_DAYS" "$NUM_SRK" \
        | ./hab4_pki_tree.sh

    popd > /dev/null

    # Copy all generated material to output directory
    cp "$CST_PATH/keys/"*.pem "$OUTPUT_DIR/keys/"    2>/dev/null || true
    cp "$CST_PATH/crts/"*.pem "$OUTPUT_DIR/crts/"    2>/dev/null || true

    log_info "Keys and certificates copied to $OUTPUT_DIR"
}

generate_srk_table() {
    log_info "Generating SRK fuse table..."

    # Build argument list for srktool: one cert per SRK slot
    CERT_LIST=()
    for i in $(seq 1 "$NUM_SRK"); do
        CERT_FILE="$OUTPUT_DIR/crts/SRK${i}_sha256_${KEY_LENGTH}_65537_v3_usr_crt.pem"
        if [ ! -f "$CERT_FILE" ]; then
            log_error "Expected cert not found: $CERT_FILE"
            log_error "Key generation may have failed or naming differs for this CST version."
            log_error "Check $OUTPUT_DIR/crts/ for actual filenames."
            exit 1
        fi
        CERT_LIST+=("$CERT_FILE")
    done

    "$CST_PATH/linux64/bin/srktool" \
        --hab_ver 4 \
        --certs "${CERT_LIST[@]}" \
        --table  "$OUTPUT_DIR/SRK_1_2_3_4_table.bin" \
        --efuse_entries "$OUTPUT_DIR/SRK_1_2_3_4_fuse.bin" \
        --format bin

    log_info "SRK table      : $OUTPUT_DIR/SRK_1_2_3_4_table.bin"
    log_info "SRK fuse values: $OUTPUT_DIR/SRK_1_2_3_4_fuse.bin"

    # Show SHA-256 of table for verification records
    echo ""
    echo "SRK table SHA-256 (record this in your key inventory):"
    sha256sum "$OUTPUT_DIR/SRK_1_2_3_4_table.bin"
}

print_fuse_values() {
    log_info "SRK fuse values (program these into device fuses via U-Boot):"
    echo ""
    echo "  # U-Boot commands to program SRK hash fuses:"
    echo "  # Bank 3, Words 0-7 = SRK hash (256 bits = 8 x 32-bit words)"
    echo ""

    for WORD in 0 1 2 3 4 5 6 7; do
        VALUE=$(dd if="$OUTPUT_DIR/SRK_1_2_3_4_fuse.bin" \
                   bs=4 skip="$WORD" count=1 2>/dev/null \
                | xxd -p -e \
                | awk '{printf "0x%08s\n", $1}')
        printf "  fuse prog -y 3 %d %s\n" "$WORD" "$VALUE"
    done

    echo ""
    echo "  # Close device (IRREVERSIBLE - do last, after validation):"
    echo "  # fuse prog -y 1 3 0x02000000"
    echo ""
}

generate_fuse_csv() {
    # Emit a CSV for use by program-srk-fuses.sh on the target Linux side
    CSV_FILE="$OUTPUT_DIR/srk_fuses.csv"
    log_info "Generating fuse CSV: $CSV_FILE"
    echo "# bank,word,value" > "$CSV_FILE"
    for WORD in 0 1 2 3 4 5 6 7; do
        VALUE=$(dd if="$OUTPUT_DIR/SRK_1_2_3_4_fuse.bin" \
                   bs=4 skip="$WORD" count=1 2>/dev/null \
                | xxd -p -e \
                | awk '{printf "0x%08s\n", $1}')
        echo "3,$WORD,$VALUE" >> "$CSV_FILE"
    done
    log_info "Fuse CSV written for use with program-srk-fuses.sh"
}

set_key_permissions() {
    log_info "Setting secure permissions on private keys..."

    # Private keys: owner read-only
    chmod 700 "$OUTPUT_DIR/keys"
    chmod 600 "$OUTPUT_DIR/keys/"*.pem

    # Public certificates: readable (needed for signing tools)
    chmod 755 "$OUTPUT_DIR/crts"
    chmod 644 "$OUTPUT_DIR/crts/"*.pem

    # Binary fuse data: readable
    chmod 644 "$OUTPUT_DIR/"*.bin 2>/dev/null || true
    chmod 644 "$OUTPUT_DIR/"*.csv 2>/dev/null || true

    log_info "Private keys (600): owner read-only"
    log_info "Public certs (644): world-readable"
}

print_summary() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  Key generation complete                                   ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Output directory: $OUTPUT_DIR"
    echo ""
    echo "Files generated:"
    find "$OUTPUT_DIR" -type f | sort | while read -r f; do
        printf "  %-60s  %s\n" "${f#$OUTPUT_DIR/}" "$(wc -c < "$f") bytes"
    done
    echo ""
    echo -e "${YELLOW}NEXT STEPS:${NC}"
    echo "  1. Verify SRK fuse values printed above"
    echo "  2. Back up $OUTPUT_DIR to encrypted offline storage (USB + safe)"
    echo "  3. Test sign a sample image and verify HAB OPEN mode before fusing"
    echo "  4. Program fuses on a test device first"
    echo "  5. Only close production devices after full validation"
    echo ""
    echo -e "${RED}WARNING: Back up these keys NOW before doing anything else.${NC}"
}

main() {
    echo "HABv4 Key Generation Script"
    echo "==========================="
    echo ""

    check_prerequisites
    security_warning
    generate_keys
    generate_srk_table
    print_fuse_values
    generate_fuse_csv
    set_key_permissions
    print_summary
}

main "$@"
